### ISSUE TITLE
Can this be installed on VMware ESXI for raspberry pi? 

### ISSUE THREAD

**Issue by RadJKW** [DeskPi-Team/deskpi#101]
I am wanting to run my deskpi as a vmware esxi server. I'm sure i can use the scripts to install deskpi.service and deskpi-shut-off.service but i am not sure which one i should use.

**Comment by jojobrogess** [comment]
Both, if they'll work. 
Deskpi.service controls the fan.
Deskpi.shutoff.service controls the power button.

**Comment by yoyojacky** [comment]
I have no idea if the esxi can running on Raspberry Pi and work with the overlay dwc2. 
here is a hint for you. 
1. OS need to support dwc2 overlay to make the Raspberry Pi recognized the daughter board and  it will enable the front USB port . 
2. DeskPi daughter board's MCU is connected to Raspberry Pi via USB-C port and it will generate a USB serial port as /dev/ttyUSB0
and the MCU will listen the signal from the Raspberry Pi . 
for example: once the Raspberry Pi send "pwm_100" to /dev/ttyUSB0,  MCU will parser the signal and the control the speed of the fan to 100% speed,  and it will cut off the power when Raspberry Pi send "poweroff" to  MCU,  it will delay for 8-10 seconds  to wait for the shut down sequence finished. 
3. The install.sh shell script will show you how to deploy those things and there are source codes in driver location. both Language C and Python)
