### ISSUE TITLE
Is anyone actually maintaining this software?

### ISSUE THREAD

**Issue by bjs-pdx** [DeskPi-Team/deskpi#103]
There are multiple posts regarding problems with the software but only crickets from the dev.  Is anyone actually maintaining this code and repository or is it just dead?  I'd really like to know since it seems nothing is getting fixed.

**Comment by jojobrogess** [comment]
It doesn't look like it, tbh.

**Comment by yoyojacky** [comment]
> There are multiple posts regarding problems with the software but only crickets from the dev. Is anyone actually maintaining this code and repository or is it just dead? I'd really like to know since it seems nothing is getting fixed.

I will follow up the case and maintain this repository .

**Comment by bjs-pdx** [comment]
So, looking at the dates on the code files, this still isn't being updated or maintained.  What a pity.  Really great case for the PI but really poor support.

**Comment by yoyojacky** [comment]
> So, looking at the dates on the code files, this still isn't being updated or maintained. What a pity. Really great case for the PI but really poor support.

sorry for my slow response. I have pushed a new brench to support bookworm right now.
