### ISSUE TITLE
deskpi lite config file location

### ISSUE THREAD

**Issue by crusader27529** [DeskPi-Team/deskpi#106]
I'd like to look at or edit the config file, but I've no idea where it is........or what it's called.

**Comment by crusader27529** [comment]
The request was to possibly change a timer value that another thread mentioned to fix the power button issue. The config.txt file is an executable script with no actual parameters to change.

Maybe a schematic of the daughter card would help so we could make the button actually do something useful. It does nothing now.

I bought this case for 2 reasons, with the primary was to be able to do a safe power shutdown. The cooling was secondary.

I have othe RPI with external PB's that cause the unit to go to a low power state after doing a shutdown, and then starting up when the button is pressed again. That functionality would be an adequate alternative function. I don't really think that the deskpi lite is actually capable to switch the power off. It probably also goes into a low power state anyway.

BTW, my other RPI autostarts after a power failure, also.

**Comment by jojobrogess** [comment]
Need to know what OS you're installing to, to know where it has been installed.

**Comment by crusader27529** [comment]
Raspios 64 bit

**Comment by jojobrogess** [comment]
from the installer `install-raspios-64bit.sh`

*******************************************************************

/usr/bin/pwmFanControl64
/usr/bin/safecutoffpower64
/usr/bin/deskpi-config

/boot/config.txt

fanDaemon="/lib/systemd/system/deskpi.service"
pwrCutOffDaemon="/lib/systemd/system/deskpi-cut-off-power.service"
