### ISSUE TITLE
Deskpi pro v2 Bluetooth

### ISSUE THREAD

**Issue by SlavaNova** [DeskPi-Team/deskpi#114]
I cannot pair some devices via bluetooth with the deskpi pro, the "Make Descoverable" is not working. without the desk I can pair with some aothe devices.
![Snap4](https://user-images.githubusercontent.com/106150648/170003000-1d977446-8468-4718-ad18-776a02e34a82.jpg)
![Snap2](https://user-images.githubusercontent.com/106150648/170003058-5126a393-99cb-43c5-a85a-e1df0872e9f4.jpg)

**Comment by jojobrogess** [comment]
It's a well known FACT at this point that this case interferes with WI-FI and Bluetooth connections. 

You'll have to go hardwired or move things closer, imo

**Comment by SlavaNova** [comment]
Thanks!
