### ISSUE TITLE
T-shaped conductive cotton missing in kit: need specs

### ISSUE THREAD

**Issue by n8willis** [DeskPi-Team/deskpi#115]
When attempting to assemble my new DeskPi Pro kit, the manual says that there is a "T shaped conductive cotton" part (meant, I think, for RF blocking).

There is no such part in my kit. I also contacted the contact address and received no reply.

Does anyone have specifications or further info about this material, to try and source a replacement elsewhere, since the company is not responding?

(Obligatory googling note: yes, I have searched. There is a fair amount of RF-proof tape to be found online; however, "conductive cotton" is not a product that turns up anywhere. Lots of false hits for exercise clothing, etc, but certainly not anything that would fill this role.)

**Comment by jojobrogess** [comment]
I think I have mine. I'll take pictures and post specs when I get home tonight.

**Comment by jojobrogess** [comment]
Measurements are in thousandths. 


![image](https://user-images.githubusercontent.com/17692472/173211920-e49ca43f-a69f-4cf4-a3aa-531e360f0d19.jpeg)

![image](https://user-images.githubusercontent.com/17692472/173211935-75f48c5c-9259-42e1-a5f9-4e097926e19e.jpeg)

![image](https://user-images.githubusercontent.com/17692472/173211947-51ce70e8-570b-4fef-ae41-2e1915182a22.jpeg)

![image](https://user-images.githubusercontent.com/17692472/173211965-92116498-31a8-49ca-9bb5-bd02e405dcfd.jpeg)

![image](https://user-images.githubusercontent.com/17692472/173211987-45584779-58dc-450c-ae1e-27e88c4521e0.jpeg)

![image](https://user-images.githubusercontent.com/17692472/173212006-39e04451-19c7-4e73-9722-ebc678db6d80.jpeg)

![image](https://user-images.githubusercontent.com/17692472/173212014-942d4a87-56be-4422-8976-ba7614eab8be.jpeg)

**Comment by n8willis** [comment]
Thanks for the reply! Especially the measurements.

So that looks like what I'd call "general-purpose" foam, but wrapped in conductive fabric.... Interesting. Does that seem like it to you, @jojobrogess ?

(if not, it certainly looks like the metallic-weave fabric is doing the lion's share of the shielding work, so that's probably the right replacement path and seems like it would get pretty close....)

**Comment by n8willis** [comment]
Oh, no problem: I literally posted it five minutes ago; was AFK.

The fabric itself looks like the same sort of stuff they put into RF-shielded wallets for protection against contactless-card-theft/spoofing; it's possible to order cheap samples that would be plenty big enough to trim up into a workaround.

Appreciate the info; hopefully any future customers will be able to find it if they end up in the same situation. 

(I may keep the issue open a bit longer just in case I turn up additional details that are relevant.)

**Comment by yoyojacky** [comment]
Please contact with our sales, they will reship the replacement for you.
