### ISSUE TITLE
Home Assistant HAOS Support

### ISSUE THREAD

**Issue by sgreenslade** [DeskPi-Team/deskpi#122]
Hi,
Does anyone have this installed and working with Home Assistant OS?

There are some instructions on how to access the underlying OS here: https://developers.home-assistant.io/docs/operating-system/debugging/
But will the shutdown scrip gracefully stop the Docker Containers?

**Comment by al-jimenez** [comment]
I have also been looking for this...   

I have found this, but have not tried it yet..... https://community.home-assistant.io/t/deskpi-pro-active-cooling-and-front-usb-ports/265136

**Comment by andymaycoates** [comment]
I also have this setup and would like the Deskpi install scripts to work with HAOS.

**Comment by yoyojacky** [comment]
please refer to this url: https://community.home-assistant.io/t/deskpi-pro-active-cooling-and-front-usb-ports/265136
