### ISSUE TITLE
Add support for EL9 (RHEL 9, Alma Linux 9, Rocky Linux 9, etc.)

### ISSUE THREAD

**Issue by Runkar** [DeskPi-Team/deskpi#124]
Hey there,

I've been playing around with the deskpi as a home server with an EL9 os (in my case alma linux) and I'm trying to get the install-script running with no luck..

I've been looking into the fedora-install-script but it seems there are some required packages missing in EL9 repositories.

Can you provide assistance or an adapted script?

Thank you!

**Comment by yoyojacky** [comment]
hi Runkar, It may not work on your EL9 due to the dtoverlay file is not compatible. sorry.
