### ISSUE TITLE
V1 Automatic Power-On After Power Fail Support

### ISSUE THREAD

**Issue by adamoutler** [DeskPi-Team/deskpi#129]
Hello,  I've found this is undocumented, but works well on V1.   A simple jumper can make the V1 unit power on after failure.

https://community.home-assistant.io/t/raspberry-pi-4b-case-with-ssd-support/243229/22

**Comment by yoyojacky** [comment]
you don't have to do this `addon` , just toggle the switch on board `always on` from `dis` to `en` will be ok!
