### ISSUE TITLE
Can this be installed on XBIAN?

### ISSUE THREAD

**Issue by GmodCentral** [DeskPi-Team/deskpi#134]
I have a RPI4.
I attempted to install this on XBIAN (a kodi mediacenter based on debian) and it mostly went well, until I try to set the fan to automatic.
It then spits-out the following error (and the fan doesn't change).

Please select speed level that you want:
It will always run at the speed level that you choosed.
---------------------------------------------------------------
1 - set fan speed level to 25%
2 - set fan speed level to 50%
3 - set fan speed level to 75%
4 - set fan speed level to 100%
5 - Turn off Fan
6 - Adjust the start speed level according to the temperature
7 - Cancel manual control and enable automatical fan control
---------------------------------------------------------------
Just input the number and press enter.
Your choice:7
Cancel manual control and enable automatical fan control
xbian@TVMaster ~ $ System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

Does this work with XBIAN or is it possible to get this to work?

**Comment by yoyojacky** [comment]
Recommend you use the Raspberry Pi OS 64bit instead XBIAN and you can just install kodi in your Raspberry Pi OS, it is the same.
