### ISSUE TITLE
DeskPi Pro install on Debian

### ISSUE THREAD

**Issue by titou4307** [DeskPi-Team/deskpi#135]
Hello
Is it possible to use the Deskpi Pro with OS Debian (not OS piOS) but Debian 64 bit

I want to take Debian image here : https://raspi.debian.net/tested-images/

The question in particulary for the config after install debian (not the command raspi-config....in Debian)

**Comment by yoyojacky** [comment]
it may not reqire raspi-config command, we have create a new one called "deskpi-config", it is just a shell script to control the fan speed and fan's behavior. you can try it on your own OS, as i know,  Raspberry pi OS is based ubuntu OS,  and ubuntu OS is based on Debian, it seems like it can work on debian any  way.
