### ISSUE TITLE
customize usb device Name in /usr/bin/pwmFanControl64

### ISSUE THREAD

**Issue by Bravd42** [DeskPi-Team/deskpi#136]
Hello,

my issue is that I'm using an additional serial USB device which beats DeskPi at startup naming itself /dev/ttyUSB0. So DeskPi is now on /dev/ttyUSB1. For manual setting of fan speeds I'm able to set serial_port='/dev/ttyUSB1' in deskpi-config, no problem. But for automatic fan control /dev/ttyUSB0 is hard coded in the precompiled /usr/bin/pwmFanControl64.

Is it possible to configure the serial port at run time in the systemd service?

Regards,
Bravd42

**Comment by yoyojacky** [comment]
Hi Bravd42, there is a C foler has the source code of C, you can just modify it and compile it on your own system will solve this problm. 
Please check the repositories drivers folder.
