### ISSUE TITLE
KrakenSDR Image

### ISSUE THREAD

**Issue by AKABigDinner** [DeskPi-Team/deskpi#144]
Currently running KrakenSDR Image      [krakensdr_pi4_220323.img.xz]

(https://github.com/krakenrf/krakensdr_doa/releases/download/V1.5/krakensdr_pi4_220323.img.xz) 
Having trouble finding what install script too use. I've have tried all of them with no luck.
Is it possible DeskPi could look into creating a script for KrakenSDR Image.

Respectfully,
Dennis

**Comment by yoyojacky** [comment]
KrakenSDR image ? let me see.
