### ISSUE TITLE
HDMI screen no longer sleeps

### ISSUE THREAD

**Issue by lfhoward** [DeskPi-Team/deskpi#145]
Hello, 
After installing DeskPi Pro 2 and running Ubuntu 22.04 64 bit on SSD rather than on the SD Card, I have run into an annoying bug. My monitor no longer sleeps when the system is Locked. When the system goes into Lock mode (after 5 minutes, or when manually locked), the HDMI monitor shuts off as expected, but a few seconds later the screen's backlight turns back on, even though the screen is blank. The backlight remains on forever until I move the mouse or press a key, and then the password box appears. This means that when locked/asleep, my monitor uses unnecessary energy and is experiencing more wear and tear than necessary. Before installing DeskPi, the backlight would remain powered off during Lock mode, as expected. This problem occurs with both HDMI ports. Since the monitor's backlight goes off when there is no signal from the computer, I am thinking that the system is sending some kind of wake-up signal to the monitor when it shouldn't. 

If other people experienced this bug, please comment below. I would love a fix for this, so I don't have to completely power down my system or manually turn off my monitor.

**Comment by yoyojacky** [comment]
Please kindly refer to this url: https://pimylifeup.com/raspberrypi-hdmi-cec/ 
DeskPi pro will not sending any wake-up signal to your Raspberry Pi, it just communicate with the serial port on Raspberry Pi.
