### ISSUE TITLE
 Safe-Shutdown 

### ISSUE THREAD

**Issue by mysiki** [DeskPi-Team/deskpi#15]
Hello,

It seem than  Safe-Shutdown  doesn't work. When the pi is UP and I press on shutdown button, nothing doing. 

When I make a long press, the power is shutdown but it's not safe for the pi.

**Comment by yoyojacky** [comment]
Oh, I’m very sorry, you may have misunderstood this safe shutdown function, and we may not describe it clearly. This is safe shutdown. After you shut down the Raspberry Pi normally, the deskpi will automatically power off, and the power will be turned off normally. The blue changes to red.
