### ISSUE TITLE
Which GPIO Pins are utilised by this device?

### ISSUE THREAD

**Issue by muckypaws** [DeskPi-Team/deskpi#150]
Hello All,

Which GPIO Pins are used for this DeskPi Pro V2 case?

I want to avoid any pins that are currently utilised (If any).  I see most of the control is via ttyUSB0 with commands sent on this channel.

Specifically, the front power control button.  As I'd like to include a safe shutdown script when pressed twice for example. 

Kind Regards
Muckypaws.

**Comment by yoyojacky** [comment]
None of the GPIO Pin  is used for this case,  the ttyUSB0 is from the USB-C on Raspberry Pi 4B and you need to enable it via using "dtoverlay=dwc2,dr_mode=host“  in /boot/config.txt file.
