### ISSUE TITLE
Same thing as "DeskPi Pro with update boards - SSD not working. #43"

### ISSUE THREAD

**Issue by cal1br8tr** [DeskPi-Team/deskpi#151]
I just bought a deskpi-pro with a m2 NVME SSD adapter card but it has the same problem. If I plug the same drive in to the pi via a USB adapter then it boots fine. If going through the USB U-link, all I see is:

/: Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
|__ Port 1: Dev 3, If 0, Class=Mass Storage, Driver=usb-storage, 5000M

did the flash update on the adapter, checked the physical. Using the disks app it sees the drive but states no media.

The ssd board shows a white light but only when the USB U-link is plugged in. What is the purpose of the touch points to the gpio pins?

When using a standard deskpi case with a 5V 4A 20W power supply, I still get the voltage error.

Couple of different issues but seems like this product is going in the junk drawer.

**Comment by john-clark** [comment]
Same.

**Comment by yoyojacky** [comment]
Oh, DeskPi pro supports  SATA SSD Only. please try to change it to SATA SSD and try again please.
