### ISSUE TITLE
White blinking LED

### ISSUE THREAD

**Issue by LPDaVinci** [DeskPi-Team/deskpi#156]
Is there any choice to disable the white blinking LED on the deskpi case, when using a sata ssd?

**Comment by gogreenpower** [comment]
I second this, very annoying

**Comment by inspector71** [comment]
Doesn't bother me. I like it. However I can imagine situations where it could be annoying. An option to disable would be sensible.

**Comment by gogreenpower** [comment]
Would de-soldering the led stop anything from working?

**Comment by inspector71** [comment]
> Would de-soldering the led stop anything from working?

Wow, that's annoying it is? I find probably the simplest choice is a piece of black electrical tape :)

**Comment by gogreenpower** [comment]
That's what I'm currently using but I like permanent solutions. I have gone to great lengths to reduce all electronic standby/on lights. Can't stand them.

**Comment by yoyojacky** [comment]
I don't recommend to de-soldering it, it is a status indicator to check if the ssd is working properly, it will blink once the ssd is writing data or system is synchronizing... if you don't like it, just put a black tape on it. LoL
