### ISSUE TITLE
need updated binaries

### ISSUE THREAD

**Issue by paulwratt** [DeskPi-Team/deskpi#160]
due to the merged PR #147 _all_ the PWM control binaries need updating in this repo

you can not just run the `Makefile` on a 64bit system, as the binary filenames used on a 64bit install are different from what are produced by default.

**Comment by yoyojacky** [comment]
yes, that's right, we are working on the new installation scripts and it will comming soon.

**Comment by yoyojacky** [comment]
I have upload new branch : feature/bookworm .  and you can try to use this one .
