### ISSUE TITLE
Deskpi drivers script not working on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by kidekoop2016** [DeskPi-Team/deskpi#161]
I have used the script for ubuntu 64

For Ubuntu 64bit OS
cd ~
git clone https://github.com/DeskPi-Team/deskpi.git
cd ~/deskpi/
chmod +x install-ubuntu-64.sh
sudo ./install-ubuntu-64.sh

And it does not work

This is the ubuntu version 

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

This is the instalation

```
root@pi2-desktop:/home/pi2/Descargas/deskpi# sudo ./install-ubuntu-64.sh
 * DeskPi Fan control script installation Start.
 * DeskPi main control service loaded.
Leyendo lista de paquetes...
Creando árbol de dependencias...
Leyendo la información de estado...
gcc ya está en su versión más reciente (4:11.2.0-1ubuntu1).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 2 no actualizados.
./install-ubuntu-64.sh: line 27: cd: /home/root/deskpi/drivers/c/: No such file or directory
cc1: fatal error: /home/root/deskpi/drivers/c/pwmControlFan.c: No such file or directory
compilation terminated.
cc1: fatal error: /home/root/deskpi/drivers/c/fanStop.c: No such file or directory
compilation terminated.
cp: cannot stat '/home/root/deskpi/drivers/c/pwmFanControl': No such file or directory
cp: cannot stat '/home/root/deskpi/drivers/c/fanStop': No such file or directory
cp: cannot stat '/home/root/deskpi/deskpi-config': No such file or directory
cp: cannot stat '/home/root/deskpi/Deskpi-uninstall': No such file or directory
chmod: cannot access '/usr/bin/pwmFanControl': No such file or directory
chmod: cannot access '/usr/bin/fanStop': No such file or directory
chmod: cannot access '/usr/bin/deskpi-config': No such file or directory
chmod: cannot access '/usr/bin/Deskpi-uninstall': No such file or directory
 * DeskPi Service configuration finished.
 * DeskPi Service Load module.
Created symlink /etc/systemd/system/multi-user.target.wants/deskpi.service → /lib/systemd/system/deskpi.service.
Created symlink /etc/systemd/system/halt.target.wants/deskpi-safeshut.service → /lib/systemd/system/deskpi-safeshut.service.
Created symlink /etc/system
```

This is the service status

```
root@pi2-desktop:/home/pi2# systemctl restart deskpi.service
root@pi2-desktop:/home/pi2# systemctl status deskpi.service
× deskpi.service - DeskPi PWM Control Fan Service
     Loaded: loaded (/lib/systemd/system/deskpi.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-11-06 21:12:25 CET; 3s ago
    Process: 2053 ExecStart=sudo /usr/bin/pwmFanControl (code=exited, status=1/FAILURE)
   Main PID: 2053 (code=exited, status=1/FAILURE)
        CPU: 28ms

nov 06 21:12:25 pi2-desktop systemd[1]: Started DeskPi PWM Control Fan Service.
nov 06 21:12:25 pi2-desktop sudo[2053]:     root : command not allowed ; PWD=/ ; USER=root ; COMMAND=/usr/bin/pwmFanControl
nov 06 21:12:25 pi2-desktop sudo[2053]: sudo: /usr/bin/pwmFanControl: command not found
nov 06 21:12:25 pi2-desktop systemd[1]: deskpi.service: Main process exited, code=exited, status=1/FAILURE
nov 06 21:12:25 pi2-desktop systemd[1]: deskpi.service: Failed with result 'exit-code'.
root@pi2-desktop:/home/pi2# 
```

I think I need to use pwmControlFan64. Right? How could I install it for 64 bits?
Thanks

**Comment by yoyojacky** [comment]
> I have used the script for ubuntu 64
> 
> For Ubuntu 64bit OS cd ~ git clone https://github.com/DeskPi-Team/deskpi.git cd ~/deskpi/ chmod +x install-ubuntu-64.sh sudo ./install-ubuntu-64.sh
> 
> And it does not work
> 
> This is the ubuntu version
> 
> ```
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.04.3 LTS
> Release:	22.04
> Codename:	jammy
> ```
> 
> This is the instalation
> 
> ```
> root@pi2-desktop:/home/pi2/Descargas/deskpi# sudo ./install-ubuntu-64.sh
>  * DeskPi Fan control script installation Start.
>  * DeskPi main control service loaded.
> Leyendo lista de paquetes...
> Creando árbol de dependencias...
> Leyendo la información de estado...
> gcc ya está en su versión más reciente (4:11.2.0-1ubuntu1).
> 0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 2 no actualizados.
> ./install-ubuntu-64.sh: line 27: cd: /home/root/deskpi/drivers/c/: No such file or directory
> cc1: fatal error: /home/root/deskpi/drivers/c/pwmControlFan.c: No such file or directory
> compilation terminated.
> cc1: fatal error: /home/root/deskpi/drivers/c/fanStop.c: No such file or directory
> compilation terminated.
> cp: cannot stat '/home/root/deskpi/drivers/c/pwmFanControl': No such file or directory
> cp: cannot stat '/home/root/deskpi/drivers/c/fanStop': No such file or directory
> cp: cannot stat '/home/root/deskpi/deskpi-config': No such file or directory
> cp: cannot stat '/home/root/deskpi/Deskpi-uninstall': No such file or directory
> chmod: cannot access '/usr/bin/pwmFanControl': No such file or directory
> chmod: cannot access '/usr/bin/fanStop': No such file or directory
> chmod: cannot access '/usr/bin/deskpi-config': No such file or directory
> chmod: cannot access '/usr/bin/Deskpi-uninstall': No such file or directory
>  * DeskPi Service configuration finished.
>  * DeskPi Service Load module.
> Created symlink /etc/systemd/system/multi-user.target.wants/deskpi.service → /lib/systemd/system/deskpi.service.
> Created symlink /etc/systemd/system/halt.target.wants/deskpi-safeshut.service → /lib/systemd/system/deskpi-safeshut.service.
> Created symlink /etc/system
> ```
> 
> This is the service status
> 
> ```
> root@pi2-desktop:/home/pi2# systemctl restart deskpi.service
> root@pi2-desktop:/home/pi2# systemctl status deskpi.service
> × deskpi.service - DeskPi PWM Control Fan Service
>      Loaded: loaded (/lib/systemd/system/deskpi.service; enabled; vendor preset: enabled)
>      Active: failed (Result: exit-code) since Mon 2023-11-06 21:12:25 CET; 3s ago
>     Process: 2053 ExecStart=sudo /usr/bin/pwmFanControl (code=exited, status=1/FAILURE)
>    Main PID: 2053 (code=exited, status=1/FAILURE)
>         CPU: 28ms
> 
> nov 06 21:12:25 pi2-desktop systemd[1]: Started DeskPi PWM Control Fan Service.
> nov 06 21:12:25 pi2-desktop sudo[2053]:     root : command not allowed ; PWD=/ ; USER=root ; COMMAND=/usr/bin/pwmFanControl
> nov 06 21:12:25 pi2-desktop sudo[2053]: sudo: /usr/bin/pwmFanControl: command not found
> nov 06 21:12:25 pi2-desktop systemd[1]: deskpi.service: Main process exited, code=exited, status=1/FAILURE
> nov 06 21:12:25 pi2-desktop systemd[1]: deskpi.service: Failed with result 'exit-code'.
> root@pi2-desktop:/home/pi2# 
> ```
> 
> I think I need to use pwmControlFan64. Right? How could I install it for 64 bits? Thanks

could you please check if the repository has been download to your root home folder ?  it seems like the pwmfancontrol is 32bit version ,you may need to change to 64bit , you can check the deskpi/drivers/c/ folder and recompile the source code with make command.. and then repleace the pwmFanControl file to pwmFanControl64 and modify the /lib/systemd/system/deskpi.service file in Execstart section, we are going to re-build the installation script ASAP.
