### ISSUE TITLE
[FR] LineageOS 20 (Android 13) support for DeskPi Pro v3

### ISSUE THREAD

**Issue by azumimuo** [DeskPi-Team/deskpi#170]
Hello..

Is there any chance to have some support for Android build?

Currently, I'm successfully enable dual front USB port by adding "dtoverlay=dwc2,dr_mode=host" in /boot/config.txt and successfully boot M.2 SATA SSD from USB 3.0 port.

I'm hoping that someone could share some android script because I do not have basic programming and I do not know how to control or start the pwm fan and also add safe-cut-off power switch features.

Thanks
Azumimuo

**Comment by yoyojacky** [comment]
sorry, it does not support android OS.

**Comment by azumimuo** [comment]
Hello again..

Since no support for Android, would you share the location of constant 3V/5V output point on-board (either than usb pin or gpio pin) power for cooling fan?

Thanks
-Azumimuo-

**Comment by yoyojacky** [comment]
Hi Azumimuo, 
You mean here ？
![087fdfd40a86138b5832b852a6e42a3](https://github.com/DeskPi-Team/deskpi/assets/6893075/ec6b7c36-50b6-4eb5-9fa2-68d02193fce9)

**Comment by yoyojacky** [comment]
or you can just use the GPIO Pin which is spread out by using FFC cable to the daughter board of deskPi pro
![image](https://github.com/DeskPi-Team/deskpi/assets/6893075/4be37e80-b5a9-4ee8-aae0-101240c8ba21)

**Comment by azumimuo** [comment]
>  Hi Azumimuo, 
> You mean here ？
> ![087fdfd40a86138b5832b852a6e42a3](https://github.com/DeskPi-Team/deskpi/assets/6893075/ec6b7c36-50b6-4eb5-9fa2-68d02193fce9)
> 

it's only activated only by working script (currently, no android supported script)

**Comment by azumimuo** [comment]
> or you can just use the GPIO Pin which is spread out by using FFC cable to the daughter board of deskPi pro
> ![image](https://github.com/DeskPi-Team/deskpi/assets/6893075/4be37e80-b5a9-4ee8-aae0-101240c8ba21)
> 

![IMG20240513205135.jpg](https://github.com/DeskPi-Team/deskpi/assets/8498014/251ddec4-50db-4904-9c9b-f76848553c09)

already done that. but don't like it.

**Comment by yoyojacky** [comment]
use GPIO instead of it ?

**Comment by azumimuo** [comment]
> use GPIO instead of it ? 
> 

yes, not connected to the internal fan connector. there's no android supported pwm fan script for DeskPi Pro v3.

**Comment by yoyojacky** [comment]
Oh ,  I see. yes ,it is hard to adding android support pwm fan script due to the variable version of android system. and it may need to recompile kernel or something I do not know.

**Comment by azumimuo** [comment]
hello Deskpi technical team & yoyojacky, are this unsoldered poin named "USB3" can give constant 5 volt?

![Uploading IMG_20240622_193453.jpg …]()

**Comment by yoyojacky** [comment]
![image](https://github.com/DeskPi-Team/deskpi/assets/6893075/f0a72298-bca4-4dc1-af50-cb1d0ce812c7)
why don't you use this Fan cable for 5V fan output ? 
or you want to use other 5v device ?
you can use GPIO on back -> 
![image](https://github.com/DeskPi-Team/deskpi/assets/6893075/44866324-f104-4b14-8533-c593d3ab9b02)

**Comment by yoyojacky** [comment]
![e0d976909b08a9d4e15633682d70dea](https://github.com/DeskPi-Team/deskpi/assets/6893075/c62a4b60-e4cd-4216-9387-dd214a7defd5)
 Here is the pin out of USB3 soldering point. 
it can provide constant 5V and GND as figure showing.
