### ISSUE TITLE
Broken RaspPi 64 bit script

### ISSUE THREAD

**Issue by kenwdelong** [DeskPi-Team/deskpi#176]
I am getting
```
root@weewx:/home/ken/deskpi/RaspberryPiOS/64bit# ./install-raspios-64bit.sh 
Initializing functions....
./install-raspios-64bit.sh: line 120: unexpected EOF while looking for matching `"'
```

Seems like there's an unabalanced double-quote at https://github.com/DeskPi-Team/deskpi/blob/master/RaspberryPiOS/64bit/install-raspios-64bit.sh#L43

**Comment by yoyojacky** [comment]
Hi kenwdelong, 
I've already update it, please use git clone to clone the latest code and try again.
