### ISSUE TITLE
Turn on RPI when power is connected

### ISSUE THREAD

**Issue by Usa89** [DeskPi-Team/deskpi#3]
Hi,

Can you setup auto boot when power is connected?

**Comment by AllonisDave** [comment]
Yes +1 for that. There are many use cases where it is desirable to autoboot after a power failure.

**Comment by emericp** [comment]
Maybe i'm wrong, but I use the jumper close to the power button to enable "Power always on mode", as I will use it as server.

**Comment by yoyojacky** [comment]
OK, we will submit your request
