### ISSUE TITLE
Problem using pwmFanControl in Ubuntu server 20.04

### ISSUE THREAD

**Issue by diego-G** [DeskPi-Team/deskpi#30]
The service doesn't get executed due to the next problem:

`sudo: unable to execute /usr/bin/pwmFanControl: No such file or directory`

I tried using the script for Ubuntu Mate but it doesn't work well. I had to execute the commands by hand. Therefore, I imagine the scripts should be prepare for Ubuntu 20.04.

**Comment by yoyojacky** [comment]
sudo cp -rf $installationfolder/drivers/c/pwmFanControl /usr/bin/pwmFanControl
sudo cp -rf $installationfolder/drivers/c/fanStop  /usr/bin/fanStop 
please copy the binary file from the installation folder. and give them execute permissions.

**Comment by diego-G** [comment]
I had to recompile the executables before compiling them. Thanks anyways!
