### ISSUE TITLE
Configuration file /lib/systemd/system/deskpi.service is marked executable.

### ISSUE THREAD

**Issue by mgrouch** [DeskPi-Team/deskpi#31]
systemd[1]: Configuration file /lib/systemd/system/deskpi.service is marked executable. Please remove executable permission bits. Proceeding anyway.

Warning after running deskpi install.sh script

**Comment by yoyojacky** [comment]
> systemd[1]: Configuration file /lib/systemd/system/deskpi.service is marked executable. Please remove executable permission bits. Proceeding anyway.
> 
> Warning after running deskpi install.sh script

OK, thanks for your tips.
