### ISSUE TITLE
DeskPi Pro - SSD is not recognized

### ISSUE THREAD

**Issue by starmagoo** [DeskPi-Team/deskpi#33]
Hello, I have purchased the DeskPi Pro and assembled it without any problems. Unfortunately, the add-on board (PCB) for the SATA SSDs does not recognize the SSDs. Therefore, I can not boot from SSD or USB. Raspberry Pi OS does not display the SSD so I assume a hardware defect.

How to solve the issue?

Greetings

**Comment by Mister-42** [comment]
Step 1) Read previous issues
Step 2) Wait for the middle of march 2021

More information [here](https://deskpi.com/products/deskpi-pro-for-raspberry-pi-4).

**Comment by starmagoo** [comment]
Thanks for the Hint. I ordered at Seeedstudio. So Seeedstudio will contact me?

**Comment by futurejones** [comment]
@yoyojacky You have closed this without answering the question about SeeedStudio.
What do the people who purchased from SeedStudio do??
