### ISSUE TITLE
SeeedStudio replacement daughterboard

### ISSUE THREAD

**Issue by futurejones** [DeskPi-Team/deskpi#34]
@yoyojacky  In many of the issues we have been told  - "please contact sales@deskpi.com to change the daughterboard."

Can you explain how customers who bought their DeskPi cases from SeeedStudio can obtain a new replacement daughterboard?

**Comment by yoyojacky** [comment]
All DeskPi malfunctioning products will be provided for replacement. Even if they are purchased from seeedstudio, you can directly contact the purchasing supplier and submit a replacement application. If it is purchased from the official deskpi website, please contact sales@deskpi.com directly.
