### ISSUE TITLE
Auto-Power-On after Power Loss

### ISSUE THREAD

**Issue by adamoutler** [DeskPi-Team/deskpi#37]
Is there a way to enable an automatic power on after power loss.  I realize it's not an advertised feature, but there must be some way to connect some test points, or replace a capacitor, and cause the device to power on automatically when power is applied? 

This case is a great form factor for a RPI Server because it is stackable and has cooling.  This is a necessary feature for a server.

**Comment by adamoutler** [comment]
What problems would this cause?  
![image](https://user-images.githubusercontent.com/527919/112239689-513fad80-8c1d-11eb-9b61-6aaaace663d7.png)

**Comment by paulpeeters** [comment]
I'm also looking for a way to automatically power on the DeskPi after a power failure. Can this be made possible somehow?

**Comment by adamoutler** [comment]
just a note: I've been running the mod successfully for about a year and it works.

@yoyojacky can you tell me the source of the signal I'm using to make this work from schematics?
