### ISSUE TITLE
Shutdown pressing power button off

### ISSUE THREAD

**Issue by jzazo** [DeskPi-Team/deskpi#42]
Hi! Is there a way to tell the OS to shutdown by pressing the power button with a short press? I tried installing acpid tools but it did not work. Any tool that can help getting a safe shutdown? Thanks.

**Comment by jzazo** [comment]
Any way we can trigger a shutdown script when pressing the button? What kind of event does it generate into the OS to configure that, similar to how it is done with GPIO? Any pointer?

**Comment by yoyojacky** [comment]
hi jzazo, it seems like you cannot do that just by only one click unless you modify the firmware on the MCU on the daughter board, but you can add another button via GPIO and write a code to detect the GPIO pin's level and send `power_off` signal to `/dev/ttyUSB0` device which created by adding `dtoverlay=dwc2,dr_mode=host` to /boot/config.txt (Raspbian OS, Other OS need to enable `dwc2` overlay to let raspberry pi can communicate with MCU on daughter board.
