### ISSUE TITLE
DeskPi Upgrade Boards - Instructions unclear

### ISSUE THREAD

**Issue by jacobacci** [DeskPi-Team/deskpi#44]
I have received my upgrade board, thanks.
In the package this item was included:

![IMG-0662](https://user-images.githubusercontent.com/10114193/119100127-ebeb1b80-ba17-11eb-8b21-4ba1b41dd03b.jpg)

However it is unclear to me where this fits. One possibility would be like this:

![IMG-0663](https://user-images.githubusercontent.com/10114193/119100201-fdccbe80-ba17-11eb-8ce2-696c06795d23.jpg)

Where is the correct location to fit this?
Thanks

**Comment by CrunchyDoodle** [comment]
You're close. I believe it goes to the left between the USB ports. I watched a couple of YouTube videos where it was demonstrated how to install it.

**Comment by jacobacci** [comment]
Thanks, I got a response from pi-mania.com.au which confirmed the following location

![InkedIMG-0663_LI](https://user-images.githubusercontent.com/10114193/119252927-0c011300-bbaf-11eb-9a53-a2d5a506c5f1.jpg)

**Comment by CrunchyDoodle** [comment]
I hate belaboring this, and here are the instructions you should have received with the upgrade.
![IMG_20210523_151612_edit_8190612962812](https://user-images.githubusercontent.com/20261525/119278491-7b402c80-bbda-11eb-9751-d8e5bd756d38.jpg)

**Comment by jacobacci** [comment]
Thanks @CrunchyDoodle 
You are not belaboring anything. You actually gave me the correct answer. I was a bit doubtful myself, as I assumed the T-piece is conductive and it would be strange to put it in contact with the solder on the bottom of the board. I will put it in correctly today.
@yoyojacky Could you possibly post the complete instructions somewhere on the DeskPi website? Thank you

**Comment by TeoTN** [comment]
The docs should mention that the previous (black) USB bridge isn't compatible with the new board, and you have to use the new USB bridge (gray)... That would save me quite some time

**Comment by jojobrogess** [comment]
AFAIK my old black one from v1 is working. I'll know more tonight when I try to enable TRIM. But when I put everything together initially, I used the black one and my SSD booted up without problems. What is different about it specifically ??

**Comment by TeoTN** [comment]
For me it wouldn't boot, throwing loads of errors on boot up time, many services (Disk Manager, Account Service, containerd, OpenBSD SSH server, Snap Daemon) crashing and eventually a long (like, really long) list of errors while accessing /dev/sda would appear on the screen and eventually kernel would go to tainted state.

**Comment by jojobrogess** [comment]
I got mine installed and working correctly without any issues, yet.. And I was able to use either bridge interchangeably without issue. Could be something else happening with your setup.

**Comment by yoyojacky** [comment]
The T-type anti-static cotton should be inserted between USB3.0 and USB2.0, this is to solve the problem of the Raspberry Pi USB interface grounding.

**Comment by yoyojacky** [comment]
> 谢谢@CrunchyDoodle
> 你没有在做任何事情。你实际上给了我正确的答案。我自己有点怀疑，因为我认为 T 型件是导电的，将它与电路板底部的焊料接触会很奇怪。我今天会正确地把它放进去。
> @yoyojacky您能否在 DeskPi 网站上的某处发布完整的说明？谢谢

OK, we are working on it.
