### ISSUE TITLE
pwmFanControl service cannot activate (Arch/Manjaro 64-Bit)

### ISSUE THREAD

**Issue by johntdavis84** [DeskPi-Team/deskpi#66]
> ~]$ systemctl status deskpi.service
> ● deskpi.service - DeskPi PWM Control Fan Service
>      Loaded: loaded (/usr/lib/systemd/system/deskpi.service; enabled; vendor preset: disabled)
>      Active: activating (start) since Thu 2021-08-26 23:14:32 CDT; 7min ago
>    Main PID: 425 (sudo)
>       Tasks: 2 (limit: 8989)
>         CPU: 181ms
>      CGroup: /system.slice/deskpi.service
>              ├─425 sudo /usr/bin/pwmControlFan64 "&"
>              └─429 /usr/bin/pwmControlFan64 "&"

On the plus side, the system boots and this doesn't seem to be consuming all resources.
On the downside, this service is clearly not activating.

I've never seen one get stuck at this stage without causing havoc.

Here's the unit file:
> ~]$ cat /usr/lib/systemd/system/deskpi.service 
> [Unit]
> Description=DeskPi PWM Control Fan Service
> After=multi-user.target
> 
> [Service]
> Type=oneshot
> RemainAfterExit=true
> ExecStart=sudo /usr/bin/pwmControlFan64 &
> 
> [Install]
> WantedBy=multi-user.target

Any ideas? I feel like I must be really close.

 @ddetton , what did you do for your unit file?

**Comment by johntdavis84** [comment]
@ddetton ,

Thanks! Making those changes to the deskpi.service file and restarting did the trick.
Do we have any idea what the changes do? I don't know much about SystemD yet, so I'm a bit lost there.
1. Type=oneshot-->simple
2. RemainAfterExit=yes-->no
3. Removing the "&" from the ExecStart prevents the process from being run in the background, but I'm not sure why that was failing before. Again, I don't know enough about SystemD yet to quite figure out what's going on.

I can't get the fans to activate automatically, but I think that's because I'm not getting the Pi hot enough. Time to overclock.

Is there a reason you went with `fanstop` instead of `safecutoffpower`?

Otherwise, the only differences between yours and the default Ubuntu 64 script are a shorter `TimeoutStartSec` and the addition of something called `final.target`. I don't understand enough about how the targets work to really know what those do, but I'm guessing they're some sort of condition hooks to tell the service to cut in and do its thing if any of the "target" conditions happen.

**Comment by yoyojacky** [comment]
try to replace `/usr/bin/pwmFanControl` with `driver/c/pwmFanControl64` , and modify `/lib/systemd/system/deskpi.service`  too.
