### ISSUE TITLE
[FR] Windows 10 support

### ISSUE THREAD

**Issue by cinadr** [DeskPi-Team/deskpi#73]
Hi!

I know there is no Windows support currently with DeskPi. Is there any chance to have some support for Windows 10-11? There is a serious - and obviously working - effort installing Windows 10 or 11 on Pi4/400. Currently I write this on W11/Edge.
[Home Page of WOR](http://worproject.ml )
[Github of WOR](https://github.com/worproject)

I have no fan control at all, even I cannot start it. Front USB not working. I have only COM1 (BCM283x Mini UART Serial Device) installed correctly. But I don't know if it is the correct serial port for fan control. Nothing happens if I enter:

`echo "pwm_100" > COM1`
nor
`set /p "pwm_100" <nul >COM1`

Can you get some details of that COM port you use in your c/python code? Baud? Which device? Is that always /dev/ttyUSB0?

Thank you,
Zsolt.

**Comment by yoyojacky** [comment]
> Hi!
> 
> I know there is no Windows support currently with DeskPi. Is there any chance to have some support for Windows 10-11? There is a serious - and obviously working - effort installing Windows 10 or 11 on Pi4/400. Currently I write this on W11/Edge. [Home Page of WOR](http://worproject.ml) [Github of WOR](https://github.com/worproject)
> 
> I have no fan control at all, even I cannot start it. Front USB not working. I have only COM1 (BCM283x Mini UART Serial Device) installed correctly. But I don't know if it is the correct serial port for fan control. Nothing happens if I enter:
> 
> `echo "pwm_100" > COM1` nor `set /p "pwm_100" <nul >COM1`
> 
> Can you get some details of that COM port you use in your c/python code? Baud? Which device? Is that always /dev/ttyUSB0?
> 
> Thank you, Zsolt.

Hi bro, 
I have tried on Windows 10 IoT but no luck. I don't know how to enable "dwc2" functions on windows os.
DeskPi pro needs the OS enable this overlay `dtoverlay=dwc2,dr_mode=host` and it will enable front USB port, and also generate a serial device via USB-C port called `/dev/ttyUSB0` which is in linux env, maybe it will be `COM` port on windows system, such as `COM1` or something, you can change the python file on `serial.Serial("COM1", baudrate=9600, timeout=30) and then try to send `pwm_100` to this `COM1` and observe the fan, if the fan spinning in 100% means it works.
