### ISSUE TITLE
Problem with Raspbian 64bits

### ISSUE THREAD

**Issue by titou4307** [DeskPi-Team/deskpi#79]
Hello

I have this problem ....

pi@docker:~/deskpi $ deskpi-config
/usr/bin/deskpi-config: ligne 11: /usr/local/lib/deskpi-log-functions: Aucun fichier ou dossier de ce type
/usr/bin/deskpi-config: ligne 44: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 45: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 46: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 47: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 48: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 49: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 50: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 51: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 52: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 53: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 54: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 55: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 56: log_action_msg : commande introuvable
Your choice:6
/usr/bin/deskpi-config: ligne 85: log_action_msg : commande introuvable
/usr/bin/deskpi-config: ligne 31: log_action_msg : commande introuvable
Current CPU Temperature: temp=42.3'C

Could you help me ??

Impossible for me to install into Raspi Os 64 bits properly
Errort message like "folder or file not exist" during the install script...

I have try many install and so at each time and at each time the same error message

**Comment by SteveBinary** [comment]
> hi all, today i am going to solve this problem, it seems like there are some bugs during merge the branch... sorry for that.

Running the newest version doesn't produce an error, but it made me suspicious that the system didn't reboot automatically. A great thing: `deskpi-config` looks like it should. No messages of "log_action_msg not found". 

But the pwnFanControl seems still broken:
![image](https://user-images.githubusercontent.com/60712092/139551821-aa77fd38-f732-464e-ba0d-0dd6b602b62e.png)
Starting it manually won't finish at all.
I don't know what to do. What is the "DeskPi PWM Control Fan Service" actually for? Only for automatic fan control?

**Comment by yoyojacky** [comment]
please use https://github.com/DeskPi-Team/deskpi/blob/master/drivers/c/pwmFanControl64 replease  `pwmFanControl` and modify the execute file name as well in /lib/systemd/system/deskpi service

**Comment by yoyojacky** [comment]
> Hi, I'm on Ubuntu-Mate (64 Bit) 20.04.3 I think my problem might be the same as this or at least similar.
> 
> I tried to run the [install-ubuntu-mate.sh script](https://github.com/DeskPi-Team/deskpi#for-ubuntu-mate-os). It produced this output: ![image](https://user-images.githubusercontent.com/60712092/139137461-a6c3488f-c17c-4cec-b0a9-7c64f247fe99.png)
> 
> Running `journalctl -xe` gave this output: ![image](https://user-images.githubusercontent.com/60712092/139137804-e2efb0bb-da60-4d1f-a82d-8cd0e4454b92.png)
> 
> So I decided to try the `deskpi-config` command with that result: ![image](https://user-images.githubusercontent.com/60712092/139138038-c59c82f5-a6a9-448e-8ce9-42725394c8d8.png)
> 
> That seems to be the same error as @titou4307's. He's on Raspbian OS and I'm on Ubuntu-Mate (64 Bit) 20.04.3 so the 64 Bit are a similarity?
> 
> Then I tried the [install-ubuntu-64.sh script](https://github.com/DeskPi-Team/deskpi#for-ubuntu-64bit-os) because of the 64 Bit. There were no visible errors, but the system didn't reboot what made me suspicious. After rebooting myself, that seems to had no effect either.
> 
> I didn't know what to do so ran the [install.sh script](https://github.com/DeskPi-Team/deskpi#for-raspbian-and-retropie-os) . It seems a little bit more general because it clones the repo for me, but it lea to this: ![image](https://user-images.githubusercontent.com/60712092/139140717-91591a32-1391-4455-ac2c-ea39dbd96a47.png) This actually rebooted the system so it seemed promising. It.Did.Not.Work.
> 
> So, then I checked the deskpi service: ![image](https://user-images.githubusercontent.com/60712092/139141953-9c3ee5cd-646a-4645-bf66-b133d9973663.png)
> 
> 1. It tries to start for at least 2min what seems a bit long
> 2. Why does it want to execute `pwmFanControl` twice?
>    It seems to stuck executing the `pwmFanControl`
>    Starting the service manually via `sudo systemctl start deskpi`, it is stuck as well.
> 
> In previous investigations (cannot reproduce it anymore) I found similar strange behavior and errors regarding the `pwmFanControl`. So the problem seems to in the pwmFanController.
> 
> (Sorry for this long message, I just wanted to point out what I discoverd)

yes, thanks for your tips , if appears log_action_msg not found means the script did not initializing  /lib/lsb/init-functions due to different OS may has different file location, i am working on it, and trying to rewrite whole scripts

**Comment by yoyojacky** [comment]
> > hi all, today i am going to solve this problem, it seems like there are some bugs during merge the branch... sorry for that.
> 
> Running the newest version doesn't produce an error, but it made me suspicious that the system didn't reboot automatically. A great thing: `deskpi-config` looks like it should. No messages of "log_action_msg not found".
> 
> But the pwnFanControl seems still broken: ![image](https://user-images.githubusercontent.com/60712092/139551821-aa77fd38-f732-464e-ba0d-0dd6b602b62e.png) Starting it manually won't finish at all. I don't know what to do. What is the "DeskPi PWM Control Fan Service" actually for? Only for automatic fan control?

please try this: https://github.com/DeskPi-Team/deskpi/blob/master/install-raspios-64bit.sh script to install deskpi drive on your 64bit OS.

**Comment by SteveBinary** [comment]
Sorry for this late answer :/

I followed your advice and tried `install-raspios-64bit.sh`. Before that, I uninstalled everything with `uninstall-raspios-64bit.sh`. At first it seemed to work and the deskpi service was running. Then I ran `deskpi-config` with option 6 an set a manual fan curve. After that, the service is failed and starting it seems to be stuck.
![image](https://user-images.githubusercontent.com/60712092/141200920-298bca24-2ef5-461a-87ee-8b0fb6245218.png)

**Comment by SteveBinary** [comment]
I want to add:
- Rebooting the Pi starts the service.
- After choosing option 7 in `deskpi-config` the service is still running.
- After choosing option 1-6 in `deskpi-config` the service is failed. So it is not limited to option 6.

**Comment by SteveBinary** [comment]
@yoyojacky  are there any updates to this?

**Comment by yoyojacky** [comment]
> @yoyojacky are there any updates to this?

Already done
