### ISSUE TITLE
[Feature Request] Support for OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by Skunk-Cabbage** [DeskPi-Team/deskpi#83]
Would it be possible to add support for OpenSUSE Tumbleweed?

Thanks

**Comment by yoyojacky** [comment]
Hi @Skunk-Cabbage , 
https://forums.opensuse.org/t/raspberry-pi-dwc2-error/120739/2 
according to this hint, you may see that, if OpenSUSE can not support dwc2 overlay well, it is imposible to enable the `/dev/ttyUSB0` device on Raspberry Pi and it will not allow your front USB port work properly, it is hard to make it works unless re-compile the kernel and build a new dwc2 overlay, it may not update in time, so we can not support this OS  right now. thanks for you asking and have a nice day!
 BTW, recommend Raspberry Pi OS 64bit right now. it is really good.
