### ISSUE TITLE
Compatibility with Debian Bullseye / 64bit

### ISSUE THREAD

**Issue by den7007** [DeskPi-Team/deskpi#89]
Can anyone confirm if the deskpi scripts work fine on the recent release of Raspi OS 64 bit (Bullseye) or the other Bullseye based OSes like DietPi?

It is a bit concerning seeing some issues here mostly for the 64bit images. I was planning on buying a unit but the lack of responses from the developers is also worrying.

**Comment by khxtendseo** [comment]
I've installed it on the 2021-10-30-raspios-bullseye-arm64-lite and it works great.  
I've also installed 2021-10-30-raspios-bullseye-arm64 and that is also working great.
