### ISSUE TITLE
Soft shutdown does not work

### ISSUE THREAD

**Issue by turacos** [DeskPi-Team/deskpi#9]
Hello,

If I press the power button for 3 seconds, the system is power off imediately instead of a soft shutdown. 
Is there any way to control the power button from a script or from a C program ?

Regards,

**Comment by yoyojacky** [comment]
if you want to shutdown and cut off the power from Raspberry Pi. 
just install deskpi driver and shut down your system as normal, click the raspberry  icon on task bar and select log off and select shutdown.  deskpi will cut off the power when your raspberry pi is shutdown.
