### ISSUE TITLE
Auto Power-On after a Power Failure

### ISSUE THREAD

**Issue by ksdhans** [DeskPi-Team/deskpi#97]
I'm using the DeskPi Pro as a server, and I'd like it to switch itself back on automatically after a power failure. This is especially important if I'm away (e.g., working remotely), so I can't just walk over and push the power button. 

Is there a way to configure the hardware to auto-power on after a power failure? Could this be added?

I'd prefer a solution that doesn't involve modifying the hardware if possible.

**Comment by paulpeeters** [comment]
I'm also interested in such a feature similar to how this can be set in the bios of a PC.

**Comment by ksdhans** [comment]
The "safe power off" script sends the string "power_off" over the serial port from the Raspberry Pi to some device on the DeskPi pro's circuit-board. I wonder if that device has other commands that could configure the power button behaviour.

We really need someone from the DeskPi-Team to respond...

**Comment by Superberti** [comment]
I would be interested in a power-on-after-reboot solution, too. For me, this is more important than the missing safe-shutdown-on-button-press feature.
Nice case, but still in some kind of beta status...

**Comment by jojobrogess** [comment]
I looked into this, I wasn't able to find a fix. 

Even with setting the power button to always on and messing with the code.

I had to resort to getting a Wi-Fi connected power hub, to "flip the switch" when the power would come back on.

**Comment by ksdhans** [comment]
@jojobrogess 
That's disappointing. How does your WiFi connected power hub "flip the switch?"

**Comment by ksdhans** [comment]
This is going to make everyone feel silly. Page 9 of the DeskPi Pro manual shows a toggle-switch that you can flick to enable "always on" mode. You can get at it by unscrewing the front panel.

![CCI_000007](https://user-images.githubusercontent.com/19198799/159495265-9c9b032b-86d3-4322-9e28-16a5023d3a0e.jpg)

**Comment by jojobrogess** [comment]
It's on the original as well.
I have a v1.

I'm pretty sure I have my case set to always on mode and after a power outage it still stays off.

**Comment by BentBanana** [comment]
I have the new v2 and it doesn’t work. Has a work around been identified?

**Comment by wpietri** [comment]
In case anybody ends up here looking for this: For the DeskPi Lite, there is a switch near the power button labeled "D - E". Putting it in the E setting enables auto power on.

**Comment by BentBanana** [comment]
I had the same issue on the DeskPi V2. What I did was put a screw driver on top of the switch housing that selects auto reboot as in the pictures above and pushed it down. It clicked into place and then worked.

**Comment by zazafree00** [comment]
> In case anybody ends up here looking for this: For the DeskPi Lite, there is a switch near the power button labeled "D - E". Putting it in the E setting enables auto power on.

Thank you, this worked for me perfectly.
