### ISSUE TITLE
HDMI/Screen crashing after opening to desktop

### ISSUE THREAD

**Issue by ilPacoOG** [DeskPi-Team/deskpi#98]
I am running Ubuntu 21.10 on my Pi 4. Either the screen or the HDMI crashes within seconds of the desktop starting up after BIOS. Is there a driver for the HDMI's on the daughter board that needs to be installed to operate correctly? Thanks!

**Comment by jojobrogess** [comment]
There aren't any supplied in the docs, so I would assume they don't get used(or come installed?)
 
But this is an interesting question I never thought of..

**Comment by yoyojacky** [comment]
you don't have to install any hdmi drivers due to it is plug and play device ....
